version: '3.9'


services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: lalith@508
      POSTGRES_DB: eventBargain
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
  admin:
    build:
      context: ./Admin
      dockerfile: Dockerfile


    ports:
      - 3000:3000
    depends_on:
      - backend
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    depends_on:
      - backend
  coordinator:
    build:
      context: ./Cordinator
      dockerfile: Dockerfile
    ports:
      - 3002:3000
    depends_on:
      - backend
  vender:
    build:
      context: ./vender
      dockerfile: Dockerfile
    ports:
      - 3003:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: sh -c "python manage.py makemigrations && python manage.py migrate &&  gunicorn --bind  0.0.0.0:8000 backend.wsgi:application"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  nginx:

    image: nginx:latest

    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client
      - admin
      - backend
      - coordinator
      - vender


