# Generated by Django 4.2 on 2023-06-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_eventtype_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venders',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
